### ISSUE TITLE
Some entities are not fetched by hass-cli

### ISSUE THREAD

**Issue by haakonstorm** [home-assistant/home-assistant-cli#272]
# Some entities (switches) not fetched by hass-cli
 
```
❯ hass-cli --version
hass-cli, version 0.8.0.dev20190820161233
```

- Latest HASSIO on RPI3B+, Zigbee over RaspBee.
- Sonoff BASIC switches (wifi) (multiple).
- Tested with several hass-cli versions, both via `homebrew` and `pip`. 

Running 
`❯ hass-cli --server https://mydomain.duckdns.org --token thetoken --insecure entity list`
**successfully** retrieves entities, but the switches from the [Sonoff component for original firmware](https://github.com/peterbuga/HASS-sonoff-ewelink) do **not** appear in the list. 

Same result for `hass-cli device list`.

**Running a bulk**
`❯ hass-cli ... service call switch.toggle`
**successfully toggles the Sonoff switches** (along with everything else..). Relevant output:

```
   -  attributes:
          device_id: '1000781892'
          friendly_name: onoffD
          rssi: -80
      context:
          id: e56ccc0804b34f29b28b06fa1c25977e
          parent_id:
          user_id: 6077e1d6074c4c8a9103d88b9885ea3a
      entity_id: switch.sonoff_1000781892
      last_changed: '2019-08-23T13:10:33.287095+00:00'
      last_updated: '2019-08-23T13:10:33.287095+00:00'
      state: on
```

# Sonoff component setup

```
username: !secret sonoff_username
password: !secret sonoff_password
scan_interval: 60
grace_period: 600
api_region: 'eu'
entity_prefix: true
debug: false
```

Please advise what I can do to provide more and better debug information.
