### ISSUE TITLE
`hass-cli lint` to sanity check states/groups etc.

### ISSUE THREAD

**Issue by maxandersen** [home-assistant/home-assistant-cli#96]
i just bump into having setup a group that I thought was all great but i noticed it reported state unknown because I made a typo for the ligts.

would be nice to have a `lint` command or similar that could check for "dumb" mistakes like this ;)

**Comment by maxandersen** [comment]
example of what it could have caught:

```
hallway_lights:
  name: Hallway Lights
  entities:
    - light.hallway_light_1
    - light.hallway_light_2
    - light.hallway_light_3
    - light.hallway_light_4
    - light.hallway_light_5
```

but all the lights were actually named `light.hallroom_light_*`
